language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.0
sudo: false
addons:
  postgresql: '9.4'
services:
  - redis-server
notifications:
  email: false
env:
  global:
    - MIX_ENV=test
    - OS_USERNAME=foo
    - OS_PASSWORD=bar
    - OS_AUTH_URL="http://example.com"
    - OS_COMPUTE_URL="http://example.com"
    - OS_IMAGE_URL="http://example.com"
    - OS_NETWORK_URL="http://example.com"
    - OS_HORIZON_URL="http://example.com"


before_script:
  - cp config/travis_ci_test.exs config/test.exs
  - mix do ecto.create, ecto.migrate
